"""add columns in task

Revision ID: a95f7a944cc1
Revises: a3d5f1e2c8b4
Create Date: 2026-03-15 23:30:58.934266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95f7a944cc1'
down_revision: Union[str, None] = 'a3d5f1e2c8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('offset_days', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('dedupe_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tasks_dedupe_key'), 'tasks', ['dedupe_key'], unique=True)
    op.add_column('transactions', sa.Column('health_score', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'health_score')
    op.drop_index(op.f('ix_tasks_dedupe_key'), table_name='tasks')
    op.drop_column('tasks', 'dedupe_key')
    op.drop_column('tasks', 'severity')
    op.drop_column('tasks', 'category')
    op.drop_column('tasks', 'offset_days')
    # ### end Alembic commands ###
