FROM node:20-alpine

WORKDIR /app
COPY apps/web/package.json apps/web/package-lock.json* apps/web/pnpm-lock.yaml* /app/

RUN npm install

COPY apps/web /app
EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]
